### ISSUE TITLE
Warrior medal does not show up when tied

### ISSUE THREAD

**Issue by davidonut3** [ezio416/tm-warrior-medals#10]
So I was playing an old TOTD map and I happened to tie the Warrior target time perfectly. It does show that I have the medal in the plugin UI on screen, as well as on the in-game menu, but when I went back to the TOTD menu that shows each track of the month,
the medal does not show up. I am not sure if this is because I tied it perfectly, but the medal did show up on other maps.

I wanted to send a message on discord but the links in the description do not work for me.

**Comment by ezio416** [comment]
I'll look into this somewhat soon. Also I fixed the Discord links, thank you!

**Comment by ezio416** [comment]
Fixed for next version
