### ISSUE TITLE
Discord 

### ISSUE THREAD

**Issue by Neitram777** [ezio416/tm-warrior-medals#7]
Hi! I wanted to go to your discord server but its not possible. I want to talk with you of the possibility to have your medals on my campaign ( short and short v2 in the club “Nocturama’s club”) 

I also want to know if you want to do annother time medal, I think it could be great to have one which is 3/4 gold to AT to give a new step for people who have all golds but can’t do some AT.

**Comment by Neitram777** [comment]
Thanks for the answer.
I think your actual formula it’s great for my campaign, 1/2 instead of 1/4 could be great to beacause there’s no champions medal, it will be the greatest challenge on my map, I let you have that decision. 
for 14/15 on my campaign I removed them because they were totally broke and not good enough. The first campaign are some of my first maps and after I made a new campaign to start again from 0, there’s only 4 maps beacause I didn’t have time to do more but asap i’ll do new ones.
Also I love to play but I’m not a really good mapper even if I love creates some maps. If you have played my maps did you like them ?

**Comment by ezio416** [comment]
I think halfway would be good then. I should have time in the next couple days to add these maps and try some of them out for myself. I will also need to make some changes to the plugin and push a new version as I didn't expect someone to request more medals so soon after release lol. I will let you know once that's done, then if you add more maps to the campaign, it should be pretty quick for me to get those medals added as well without a plugin update!

**Comment by Neitram777** [comment]
That sounds good. 
I was searching for a long time to get some new medals in the game so your work is amazing for me, I love it! I would have loved to do it myself but I can't lol I’m a noob !
thank you for all.

**Comment by ezio416** [comment]
Hey, sorry it's been a while but I took a break from TM and have had to focus on other things. I've added Warrior medals to your campaigns now and they do show up in the plugin, but I still need to work on some things so they display separately from the official discovery campaigns. I decided on halfway between AT and world record, and I have a system in place now that lets me easily change that and add more.

By the way I've played a few of the maps and I am enjoying them! I will try to get top 5 on as many as I can

**Comment by Neitram777** [comment]
Hey, no problem. I just checked it. Thats Nice! Thank you for that medal. I
love it!! 🥰

Le mar. 17 sept. 2024 à 01:36, Ezio Mariani ***@***.***> a
écrit :

**Comment by ezio416** [comment]
Still working through the plugin design stuff, but I'm playing through the campaign and I just wanted to show you this lol, fun maps
![image](https://github.com/user-attachments/assets/bde522fb-939c-45d6-8304-9cdea60e365c)

**Comment by ezio416** [comment]
fixed for next version

**Comment by Neitram777** [comment]
Ahah Gg, thank you for playing !

Le ven. 20 sept. 2024 à 01:04, Ezio Mariani ***@***.***> a
écrit :
